cache: bundler
language: ruby
rvm:
  - 2.7
  - 2.6.5

env:
  - ACTIVE_RECORD_VERSION='5.2.4.1'
  - ACTIVE_RECORD_VERSION='6.0.2.1'

script:
  - bundle exec rspec

before_install:
  - rm Gemfile.lock
  - gem install bundler -v '~> 1.17'